"""initial db configs

Revision ID: 57d8e90cb98e
Revises: 
Create Date: 2025-03-20 15:06:57.608366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57d8e90cb98e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('uri', sa.String(length=512), nullable=False),
    sa.Column('features', sa.String(length=1024), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('task_type', sa.Enum('classification', 'regression', name='tasktype'), nullable=False),
    sa.Column('data_format', sa.String(length=128), nullable=True),
    sa.Column('estimated_rows', sa.Integer(), nullable=True),
    sa.Column('estimated_size_mb', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasource_name'), 'datasource', ['name'], unique=False)
    op.create_table('model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('uri', sa.String(length=512), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('understanding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_datasource', sa.Integer(), nullable=True),
    sa.Column('id_model', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_datasource'], ['datasource.id'], ),
    sa.ForeignKeyConstraint(['id_model'], ['model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('info_arguments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('understanding_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('algorithm', sa.Enum('ale', 'ensemble', 'gpx', 'knn', 'lime', 'linear', 'logit', 'shap', 'tree', name='algorithm'), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('result', sa.String(length=512), nullable=True),
    sa.Column('result_type', sa.String(length=64), nullable=True),
    sa.Column('celery_task_id', sa.String(length=155), nullable=True),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['understanding_id'], ['understanding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('info_arguments')
    op.drop_table('understanding')
    op.drop_table('model')
    op.drop_index(op.f('ix_datasource_name'), table_name='datasource')
    op.drop_table('datasource')
    # ### end Alembic commands ###
